
trigger: none

name: deploy-finance-tracker-$(Build.BuildId)

resources:
  pipelines:
  - pipeline: build-finance
    source: build-finance-tracker

variables:
- group: project-vars

pool:
  name: Default

stages:
- stage: deploy
  displayName: Deploy to Container Apps
  jobs:
  - job: deploy
    displayName: Deploy
    steps:
    - checkout: self
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'finance-home-tracker'
        imageToDeploy: "mikitasz/finance-tracker:$(resources.pipeline.build-finance.runName)"
        containerAppName: 'pl-finance-tracker'
        resourceGroup: 'rg-pl-finance-tracher'
        environmentVariables: redirectURL="$(redirectURL)" GITHUB_CLIENT_ID="$(GITHUB_CLIENT_ID)" GITHUB_CLIENT_SECRET="$(GITHUB_CLIENT_SECRET)"