
pr: 
name: $(Build.BuildId)
  
pool:
  name: Default

stages:
- stage: build
  displayName: Build finance-tracker
  jobs:
  - job: Docker_build
    displayName: Build and push an image to container registry
    steps:
    - checkout: self
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      inputs:
        containerRegistry: Docker Hub
        command: 'buildAndPush' # 'buildAndPush' | 'build' | 'push' | 'login' | 'logout' | 'start' | 'stop'. Required. Command. Default: buildAndPush.
        Dockerfile: 'Dockerfile' # string. Requi
        buildContext: "."
        repository: mikitasz/finance-tracker
        tags: $(Build.BuildId)