env: "local"
db:
  host: "127.0.0.1"
  user: "root"
  password: "admin"
  name: "finance"
  port: 3306
  
jwt:
  secret: "your-secret-key"
  access_token_expiry: 15m
  refresh_token_expiry: 7d

server:
  host: "127.0.0.1"
  port: 8080

logging:
  level: "debug"
  format: "json"
  output: "stdout"